### ISSUE TITLE
Enforce-MFA doesn’t work as expected when used in post login flow

### ISSUE THREAD

**Issue by jirutka** [netzbegruenung/keycloak-mfa-plugins#112]
I’ve configured it exactly as described in the readme, but I use this authentication flow as the Identity Provider’s post login flow.

```
- MFA Wrapper Flow
-- MFA-Authenticate-subflow CONDITIONAL
--- Condition - user configured REQUIRED
--- OTP ALTERNATIVE
--- WebAuthn ALTERNATIVE

-- Register-MFA-subflow CONDITIONAL
--- Condition - user configured REQUIRED
--- Enforce-MFA REQUIRED
```

Even when the user has Passkeys enrolled, Keycloak always shows them the Enforce-MFA page with the selection of 2FA methods to configure.

**Comment by melegiul** [comment]
> but I use this authentication flow as the Identity Provider’s post login flow.

Thanks for your report. Could you please explain what that means? Or even better provide the full authentication flow setup?

**Comment by damien-d-gerard** [comment]
Hello

Same problem here with the last version:

When you setup the flow in the "Post login flow" on the identity provider section I got the following error message:

025-04-07 15:26:01,882 WARN [org.keycloak.services] (executor-thread-41) KC-SERVICES0013: Failed authentication: org.keycloak.authentication.AuthenticationFlowException
at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1085)
at org.keycloak.services.resources.LoginActionsService$1.authenticateOnly(LoginActionsService.java:919)
at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:912)
at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:380)
at org.keycloak.services.resources.LoginActionsService.brokerLoginFlow(LoginActionsService.java:951)
at org.keycloak.services.resources.LoginActionsService.postBrokerLoginGet(LoginActionsService.java:845)
at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$postBrokerLoginGet_0fc2f32e2c3d1824f9811e876cdded93716d0c79.invoke(Unknown Source)
at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)

![Image](https://github.com/user-attachments/assets/2b3fad5e-475d-49c5-9818-bd5433eda045)

**Comment by Romain7495** [comment]
I am experiencing the exact same issue.

I have implemented step-up authentication. In certain cases, after logging in via an identity provider (e.g., Google), I need to enforce 2FA for access to specific pages.

To achieve this, I added a post-login flow to the google identity provider.
In this flow, we included the following step:

![Image](https://github.com/user-attachments/assets/fd1efc30-f37b-41ed-9b99-6e7bff7eb783)

However, this results in the following error:

![Image](https://github.com/user-attachments/assets/34d19c02-70cd-4465-9580-ebf827aa3390)

Meanwhile, when using the Browser Flow (instead of post-login flow), the 2FA step works perfectly as expected.

**Comment by damien-d-gerard** [comment]
Hello

Indeed the plugin is not working with post login flow. Only browser flow is supported.


I have chance the mecanism to find the correct flow: 

package netzbegruenung.keycloak.enforce_mfa;

import jakarta.ws.rs.core.MultivaluedMap;
import jakarta.ws.rs.core.Response;
import org.jboss.logging.Logger;
import org.keycloak.authentication.*;
import org.keycloak.authentication.authenticators.conditional.ConditionalAuthenticator;
import org.keycloak.models.*;
import org.keycloak.models.utils.AuthenticationFlowResolver;
import org.keycloak.sessions.AuthenticationSessionModel;

import java.util.LinkedList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class EnforceMfaAuthenticator implements Authenticator {
    private static final Logger logger = Logger.getLogger(EnforceMfaAuthenticator.class);

    private static final String FORM_PARAM_MFA_METHOD = "mfaMethod";
    private static final String LOCALIZATION_PREFIX = "enforceMfa";

    public static final String CONFIG_OPTIONAL_NAME = "mfaSetupOptional";
    public static final Boolean CONFIG_OPTIONAL_DEFAULT_VALUE = false;

    @Override
    public void authenticate(AuthenticationFlowContext context) {
        List<RequiredActionProviderModel> requiredActions = getAllRequiredActions(context);

        if (requiredActions.isEmpty()) {
            logger.errorv(
                "No supported required actions enabled for user {0} in realm {1}",
                context.getAuthenticationSession().getAuthenticatedUser().getId(),
                context.getRealm().getName()
            );
            Response errorResponse = context.form()
                .setError("enforceMfaIllegalState")
                .createForm("enforce-mfa.ftl");
            context.failure(AuthenticationFlowError.INTERNAL_ERROR, errorResponse);
        } else {
            Response challenge = context.form()
                .setAttribute("mfa", requiredActions)
                .setAttribute("isSetupOptional", isSetupOptional(context.getAuthenticatorConfig()))
                .setAttribute("localizationPrefix", LOCALIZATION_PREFIX)
                .createForm("enforce-mfa.ftl");
            context.challenge(challenge);
        }
    }

    private List<RequiredActionProviderModel> getAllRequiredActions(AuthenticationFlowContext context) {
        List<RequiredActionProviderModel> alternativeRequiredActions = new LinkedList<>();
        getExecutions(context.getSession(), context.getRealm(), context.getExecution())
            .forEachOrdered(e -> {
                if (e.isAlternative()) {
                    alternativeRequiredActions.addAll(getRequiredActions(context, e));
                }
            });
        return alternativeRequiredActions;
    }

    private Stream<AuthenticationExecutionModel> getExecutions(KeycloakSession session, RealmModel realm, AuthenticationExecutionModel execution) {
        AuthenticationExecutionModel baseExecution = getBaseExecutionRecursive(session, realm, execution);
        return realm.getAuthenticationExecutionsStream(baseExecution.getFlowId())
            .filter(e -> !isConditionalExecution(session, e))
            .filter(e -> !Objects.equals(execution.getId(), e.getId()) && !e.isAuthenticatorFlow());
    }

    private AuthenticationExecutionModel getBaseExecutionRecursive(KeycloakSession session, RealmModel realm, AuthenticationExecutionModel currentExecution) {
        AuthenticationExecutionModel parent = findParentExecution(realm, currentExecution);
        while (parent != null && !parent.isAuthenticatorFlow()) {
            parent = findParentExecution(realm, parent);
        }
        if (parent == null) {
            throw new IllegalStateException("Cannot determine base authenticator flow for EnforceMFA. Check the parent subflow structure.");
        }
        return parent;
    }

    private AuthenticationExecutionModel findParentExecution(RealmModel realm, AuthenticationExecutionModel execution) {
        if (execution.getParentFlow() == null) {
            return null;
        }
        return realm.getAuthenticationExecutionsStream(execution.getParentFlow())
            .filter(e -> execution.getParentFlow().equals(e.getFlowId()))
            .findFirst()
            .orElse(null);
    }

    private boolean isConditionalExecution(KeycloakSession session, AuthenticationExecutionModel e) {
        AuthenticatorFactory factory = (AuthenticatorFactory) session.getKeycloakSessionFactory()
            .getProviderFactory(Authenticator.class, e.getAuthenticator());
        if (factory != null) {
            Authenticator auth = factory.create(session);
            return (auth instanceof ConditionalAuthenticator);
        }
        return false;
    }

    private List<RequiredActionProviderModel> getRequiredActions(AuthenticationFlowContext context, AuthenticationExecutionModel e) {
        AuthenticatorFactory factory = (AuthenticatorFactory) context.getSession().getKeycloakSessionFactory()
            .getProviderFactory(Authenticator.class, e.getAuthenticator());
        Authenticator authenticator = factory.create(context.getSession());
        return authenticator.getRequiredActions(context.getSession())
            .stream()
            .map(f -> context.getRealm().getRequiredActionProviderByAlias(f.getId()))
            .filter(Objects::nonNull)
            .collect(Collectors.toList());
    }

    @Override
    public void action(AuthenticationFlowContext context) {
        MultivaluedMap<String, String> decodedFormParameters = context.getHttpRequest().getDecodedFormParameters();
        if (isSetupOptional(context.getAuthenticatorConfig()) &&
            (!decodedFormParameters.containsKey(FORM_PARAM_MFA_METHOD) || decodedFormParameters.getFirst(FORM_PARAM_MFA_METHOD).isBlank())) {
            context.success();
            return;
        }

        if (!decodedFormParameters.containsKey(FORM_PARAM_MFA_METHOD)) {
            context.challenge(context.form().createErrorPage(Response.Status.BAD_REQUEST));
            context.failure(AuthenticationFlowError.CREDENTIAL_SETUP_REQUIRED);
            return;
        }

        String action = decodedFormParameters.getFirst(FORM_PARAM_MFA_METHOD);
        Stream<String> requiredActions = getAllRequiredActions(context).stream()
            .map(RequiredActionProviderModel::getProviderId);
        if (requiredActions.noneMatch(it -> it.equals(action))) {
            context.challenge(context.form().createErrorPage(Response.Status.BAD_REQUEST));
            context.failure(AuthenticationFlowError.CREDENTIAL_SETUP_REQUIRED);
            return;
        }

        AuthenticationSessionModel authenticationSession = context.getAuthenticationSession();
        if (!authenticationSession.getRequiredActions().contains(action)) {
            authenticationSession.addRequiredAction(action);
        }
        context.success();
    }

    @Override
    public boolean requiresUser() {
        return true;
    }

    @Override
    public boolean configuredFor(KeycloakSession session, RealmModel realm, UserModel user) {
        Optional<AuthenticationExecutionModel> myExecution = findMyExecution(session, realm);
        if (myExecution.isEmpty()) {
            logger.warn("EnforceMfaAuthenticator: unable to find my execution in the realm flows.");
            return false;
        }

        return getExecutions(session, realm, myExecution.get())
            .noneMatch(e -> isAuthenticatorConfiguredFor(session, realm, user, e));
    }

    private Optional<AuthenticationExecutionModel> findMyExecution(KeycloakSession session, RealmModel realm) {
        return realm.getAuthenticationFlowsStream()
            .flatMap(flow -> realm.getAuthenticationExecutionsStream(flow.getId()))
            .filter(e -> EnforceMfaAuthenticatorFactory.PROVIDER_ID.equals(e.getAuthenticator()))
            .findFirst();
    }

    private boolean isAuthenticatorConfiguredFor(KeycloakSession session, RealmModel realm, UserModel user, AuthenticationExecutionModel e) {
        AuthenticatorFactory factory = (AuthenticatorFactory) session.getKeycloakSessionFactory()
            .getProviderFactory(Authenticator.class, e.getAuthenticator());
        Authenticator authenticator = factory.create(session);
        return authenticator.configuredFor(session, realm, user);
    }

    private boolean isSetupOptional(AuthenticatorConfigModel config) {
        return Optional.ofNullable(config)
            .map(AuthenticatorConfigModel::getConfig)
            .map(c -> c.getOrDefault(CONFIG_OPTIONAL_NAME, String.valueOf(CONFIG_OPTIONAL_DEFAULT_VALUE)))
            .map(Boolean::parseBoolean)
            .orElse(CONFIG_OPTIONAL_DEFAULT_VALUE);
    }

    @Override
    public void setRequiredActions(KeycloakSession keycloakSession, RealmModel realmModel, UserModel userModel) {
        // no-op
    }

    @Override
    public void close() {
        // no-op
    }
}

**Comment by Romain7495** [comment]
thanks @damien-d-gerard, should we propose a PR then ?

**Comment by damien-d-gerard** [comment]
Up to you. Not really sure that it's the best way to do this.
Maybe have a feedback from core dev team will be appreciated

**Comment by melegiul** [comment]
Sure. PRs are welcome. I had no time to look into the details yet. I believe you that there is a problem in the post login flow.

**Comment by Romain7495** [comment]
No more issue on my side, before taking my screenshot, I was testing only with `Recovery Code` (and not otp form)

Recovery Code requyired action is not listed in 

```	
private List<RequiredActionProviderModel> getAllRequiredActions(AuthenticationFlowContext context) {
		List<RequiredActionProviderModel> alternativeRequiredActions = new LinkedList<>();

		getExecutions(context.getSession(), context.getRealm(), context.getExecution())
			.forEachOrdered(e -> {
				if (e.isAlternative()) {
					alternativeRequiredActions.addAll(getRequiredActions(context, e));
				}
			});
		return alternativeRequiredActions;
	}
```

Thanks for discussion
