### ISSUE TITLE
Not able to migrate users and use the SMS (will help to complete future pull request with config guide)

### ISSUE THREAD

**Issue by tbaragao** [netzbegruenung/keycloak-mfa-plugins#69]
Hey guys, first of all, thanks for keep the implementation and share this repository.

I'm working in a project that needs to replace the current Auth Service for Keycloak with SMS as MFA.

I'm trying to use your plugin, but even watching the Niko Kobler videos and reading the repository README. i'm facing a lot of doubts and problems to implement it.

Thinking on that, i'm forking the repository to update the README with all the instructions to implement it, and help eveyone that needs to have it in their Keycloak. 

I'll start adding here some questions and explaining my steps.

### Configuration Guide - Part 1
- I have the Keycloak running in a Docker Container (i'll add the steps to install it in the ReadMe too)
- To be able to use the plugin, you need to have an User Attibute called 'mobile_number' to store the phone numbers. This can be done using the User profile or using User Attributes
![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/10468125/6af68ff6-2a60-4480-a873-e717f083e855)
**I've the User Profile Attirbute set as mobile_number, but in the docker logs, looks like the user number is not identified**
![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/10468125/70e6ce0a-0c07-4ac8-96aa-568dc7ce1a36)

- Go to Authentication > Flows >  Duplicate the 'browser' flow - I've set the name as 'browser with sms'
![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/10468125/8e48e103-f576-4dcf-9256-dfddaf99457a)
![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/10468125/52157ef8-0581-4caa-b9a7-fad3584ec276)

- On 'browser with sms forms' step, click over the + and add a new step
![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/10468125/7d8b86de-6ba2-4057-aa96-de1c151dac00)

- Search by 'SMS Authentication (2FA)' and click on Add button
![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/10468125/0417b3b5-a028-417f-82e4-266f26d8b219)

- Drag and Drop the added step to under the Useranme Password Form
![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/10468125/e0247251-fdbf-4fd3-8d68-b0d2eac6d67a)

- Change the to 'Required' and click over the engine to Edit the plugin settings
![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/10468125/cead0f80-42a5-4fc9-8833-95a7fad15352)

- Set the alias as 'sms-2fa' and click save
![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/10468125/47630fb6-fdc2-4e54-bf74-1891dbb1f393)

- Go back to Authentication Flows page, find the create flow, click over the settings and 'Bind Flow' option
![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/10468125/1f66d961-77c3-49d1-b727-4177d609157f)
![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/10468125/679649fc-7bdf-4741-986b-e7b310ce84c8)

- This is the basic configuration to allow you to test before configure you SMS Api Service.

### Errors with the configuration above

- When i'm creating a new user (using the keycloak sign-up form), the SMS Code step don't appear. The user is created, but any SMS is sent.
- When i tried to sign-in using the new user created, i wasn't able, and got the following error logged in the docker logs
`2024-03-09 10:22:28 2024-03-09 13:22:28,935 WARN  [org.keycloak.services] (executor-thread-337) KC-SERVICES0013: Failed authentication: org.keycloak.authentication.AuthenticationFlowException: authenticator: mobile-number-authenticator
2024-03-09 10:22:28     at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:432)
2024-03-09 10:22:28     at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:249)
2024-03-09 10:22:28     at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:380)
2024-03-09 10:22:28     at org.keycloak.authentication.DefaultAuthenticationFlow.continueAuthenticationAfterSuccessfulAction(DefaultAuthenticationFlow.java:181)
2024-03-09 10:22:28     at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:157)
2024-03-09 10:22:28     at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:988)
2024-03-09 10:22:28     at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:362)
2024-03-09 10:22:28     at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:333)
2024-03-09 10:22:28     at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:325)
2024-03-09 10:22:28     at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:390)
2024-03-09 10:22:28     at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$authenticateForm_32b8e198ac3110abd1d5774e83a4cf87858129f4.invoke(Unknown Source)
2024-03-09 10:22:28     at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
2024-03-09 10:22:28     at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
2024-03-09 10:22:28     at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
2024-03-09 10:22:28     at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
2024-03-09 10:22:28     at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
2024-03-09 10:22:28     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
2024-03-09 10:22:28     at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2024-03-09 10:22:28     at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2024-03-09 10:22:28     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-03-09 10:22:28     at java.base/java.lang.Thread.run(Thread.java:840)`

### What i did to fix the settings
- Open the Realm Authentication page, under the Required Actions, turned on the 'Phone Validation' option
![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/10468125/e40e078e-4792-4bf4-87e2-3157d0e8c5cc)

- With that, after create a new user, the SMS Code page starts to appear
![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/10468125/1f4a2a8e-0543-4283-b341-3fae3536214c)
![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/10468125/fb07f6a1-f496-4284-8995-269b178fcf05)

- And i've got this in the docker logs
![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/10468125/0df6fba3-81cb-428b-85d8-6db4e2e068ae)

- Now, **FOR NEW USERS** i'm able to use the SMS CODE.

### More questions with this basic settings
I've noticed that the created user got the following credentials
![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/10468125/c015a6f1-4045-4bac-8e46-00058fc6f6c0)

I think, that was that allow the user login using the SMS 2FA. 

But as mentionated at the very beggining, i'm migrating existent users to the Keycloak using the Keycloak Rest Api. 

Tried to add this credential throw the api, and i'm getting this errror:
![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/10468125/f8af09f1-f48f-47fd-8e77-8f84a85fb984)

**How can i add the Mobile-number credential to the migrated users and allow them use the SMS Code flow?** 

Because if i follow the above steps and don't add the credential, when i trying to login, i'm getting the following error:

`2024-03-09 10:48:25 2024-03-09 13:48:25,741 WARN  [org.keycloak.services] (executor-thread-358) KC-SERVICES0013: Failed authentication: org.keycloak.authentication.AuthenticationFlowException: authenticator: mobile-number-authenticator
2024-03-09 10:48:25     at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:432)
2024-03-09 10:48:25     at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:249)
2024-03-09 10:48:25     at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:380)
2024-03-09 10:48:25     at org.keycloak.authentication.DefaultAuthenticationFlow.continueAuthenticationAfterSuccessfulAction(DefaultAuthenticationFlow.java:181)
2024-03-09 10:48:25     at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:157)
2024-03-09 10:48:25     at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:988)
2024-03-09 10:48:25     at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:362)
2024-03-09 10:48:25     at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:333)
2024-03-09 10:48:25     at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:325)
2024-03-09 10:48:25     at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:390)
2024-03-09 10:48:25     at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$authenticateForm_32b8e198ac3110abd1d5774e83a4cf87858129f4.invoke(Unknown Source)
2024-03-09 10:48:25     at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
2024-03-09 10:48:25     at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
2024-03-09 10:48:25     at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
2024-03-09 10:48:25     at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
2024-03-09 10:48:25     at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
2024-03-09 10:48:25     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
2024-03-09 10:48:25     at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2024-03-09 10:48:25     at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2024-03-09 10:48:25     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-03-09 10:48:25     at java.base/java.lang.Thread.run(Thread.java:840)`

Thanks in advanced, I know it's a lot of information, but i really need some help here to implement it.

**Comment by melegiul** [comment]
I'm not 100% sure. Maybe you could try to pack the SMS-Authenticator into a conditional subflow with condition "user configured - required" to pass that error. Hope that helps.

**Comment by tbaragao** [comment]
Hey @melegiul, i was able to identify how to set this up. I saw the current main branch is not the last one (that generatted the 23.0.7 jar). Have you some idea when the app-authenticator branch will be merged in the main?

**Comment by dsputnikk** [comment]
@tbaragao I have the same problem. I have mobile_number as an attribute and the latest jar from this repo. I take the exact same steps but after I put in username/pass I get a "Cannot login, credential setup required." - despite the fact that my user has a mobile_number field present and set.

I tried turning the Phone Validation toggle on as you said, but no luck.

Sure you didn't do anything else to fix it?

**Comment by dsputnikk** [comment]
@tbaragao in relation to your solution, would this not be easier to migrate your users?: https://github.com/daniel-frak/keycloak-user-migration?tab=readme-ov-file

**Comment by dsputnikk** [comment]
> Hey @dsputnikk, i've identified all the steps to have it working and now i'm working on over some guide to do a pull request here. The fact that the steps in the read me right now doesn't explain the steps and the real configuration. For example, fo me, that i'm using the User Profile enabled, i don't need to configure the mobile_number attribute, it's generated automatically.
> 
> I'm just wating the response from @melegiul about to close the branch app-authenticator that was that generate the current .jar versions.

Would love to hear what you managed to accomplish.

I just got this fork wired up myself and successfully pulling users in via the legacy REST endpoint (which is reaching out to a legacy SQL app for credentials). It appears to work - but I'm a bit confused. On one the docs seem to imply that its just metadata that gets synced across

**Comment by melegiul** [comment]
> Hey @melegiul, i was able to identify how to set this up. I saw the current main branch is not the last one (that generatted the 23.0.7 jar). Have you some idea when the app-authenticator branch will be merged in the main?

Unfortunately I can't say that for sure in the moment. We want some more improvements to be done: https://github.com/netzbegruenung/keycloak-mfa-plugins/pull/63#issuecomment-1816379363

But yes you are right. Latest Keycloak support up to 23 is on this branch at the moment.

**Comment by svenseeberg** [comment]
We're now working on KC 24 support :+1:

**Comment by dsputnikk** [comment]
Can't wait

**Comment by melegiul** [comment]
> Hey @dsputnikk, i've identified all the steps to have it working and now i'm working on over some guide to do a pull request here. The fact that the steps in the read me right now doesn't explain the steps and the real configuration. For example, fo me, that i'm using the User Profile enabled, i don't need to configure the mobile_number attribute, it's generated automatically.
> 
> I'm just wating the response from @melegiul about to close the branch app-authenticator that was that generate the current .jar versions.

The app-authenticator is now merged into the main branch to better reflect the current state of the project. Sorry for the confusion.

And you are right. mobile_number is not a user attribute, it is a credential, which you can mange (delete, show) like any other credentials here `/admin/master/console/#/realm-name/users/user-id/credentials`. Changing and creating is not supported for now, but planned in the future.

I have also added some missing parts in the readme to make the setup more clear:
https://github.com/netzbegruenung/keycloak-mfa-plugins/commit/e6b54f72fdd2d82425691451e90d931dc5f85460

Of course any pull request for further improvements are welcome anytime.

**Comment by dsputnikk** [comment]
I have sms configured and OTP app. Users with both have the choice of either/or.

 Is there a way to force users without a OTP app setup to also configure the OTP method (like your force 2fa) if they don't have one?

**Comment by svenseeberg** [comment]
> Is there a way to force users without a OTP app setup to also configure the OTP method (like your force 2fa) if they don't have one?

Forcing TOTP is currently not supported, no. Please open a new issue for that. But I don't think that this feature would be highly important for us at least.

**Comment by svenseeberg** [comment]
@tbaragao is this issue solved for you with KC 24 support? If yes, we can close it.

**Comment by melegiul** [comment]
> > Is there a way to force users without a OTP app setup to also configure the OTP method (like your force 2fa) if they don't have one?
> 
> Forcing TOTP specifically is currently not supported, no. Please open a new issue for that. But I don't think that this feature would be highly important for us at least.

Actually you could try this plugin: https://github.com/netzbegruenung/keycloak-mfa-plugins/tree/main/enforce-mfa

The plugin enforces the users to set up at least one 2FA method. The choices available can be customized by your flow.

![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/47010475/3aa68506-c43f-4ec0-8a0f-190ab995cebd)


For example if you have WebAuthn and OTP, the users must choose between one of them if none is enabled.

![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/47010475/b3c26639-f24d-470e-b412-70c7cc978ce0)

**Comment by tbaragao** [comment]
@svenseeberg Validate it, and i've got this working. Very soon i'll push an PR with the guide. Thank you so much!

**Comment by dsputnikk** [comment]
Sorry to reopen - I'm still unclear @tbaragao - how did you get mobile_number populated as a credential?
